from random import randint
from turtle import Turtle

t1 = Turtle()
t1.color('red')
t1.shape('turtle')
t1.penup()
t1.goto(-100, 100)
t1.pendown()
t2 = Turtle()
t2.color('green')
t2.shape('classic')
t2.penup()
t2.goto(-100, 80)
t2.pendown()
t3 = Turtle()
t3.color('yellow')
t3.shape('circle')
t3.penup()
t3.goto(-100, 60)
t3.pendown()
for movement in range(100):
    t1.forward(randint(1, 5))
    t2.forward(randint(1, 5))
    t3.forward(randint(1, 5))
input("Press Enter to continue...")
